Taskflow2
DeustoPWEB2019/documentacion pull request #10
Opened 2019-11-22 10:35 UTC by olatzbalda

2019-11-25 09:50 UTC, mberasategi commented
Los diagramas están bien explicados, pero os falta un poco más de abstracción en la representación gráfica (son demasiado literales). He añadido dos ejemplos para que os hagáis una idea de lo que quiero decir: [comentarios.svg](/DeustoPWEB2019/documentacion/blob/Sit-Map-y-Task-flow-2/estrategiacontenidos/comentarios.svg) y [compartir-en-redes.svg](/DeustoPWEB2019/documentacion/blob/Sit-Map-y-Task-flow-2/estrategiacontenidos/compartir-en-redes.svg).

No hace falta que los hagáis _digitalmente_ (aunque, si queréis, yo los he hecho usando [Draw.io](http://draw.io); podéis probar), pero intentad hacer una represntación parecida para "Me gusta" y el buscador.

2019-11-25 09:51 UTC, mirenbz requested changes
Los diagramas están bien explicados, pero os falta un poco más de abstracción en la representación gráfica (son demasiado literales). He añadido dos ejemplos para que os hagáis una idea de lo que quiero decir: [comentarios.svg](/DeustoPWEB2019/documentacion/blob/Sit-Map-y-Task-flow-2/estrategiacontenidos/comentarios.svg) y [compartir-en-redes.svg](/DeustoPWEB2019/documentacion/blob/Sit-Map-y-Task-flow-2/estrategiacontenidos/compartir-en-redes.svg).

No hace falta que los hagáis _digitalmente_ (aunque, si queréis, yo los he hecho usando [Draw.io](http://draw.io); podéis probar), pero intentad hacer una represntación parecida para "Me gusta" y el buscador.

2019-11-25 09:59 UTC, mberasategi commented
También falta que añadáis el mapa del sitio de la nueva versión. Como la vez anterior, con una lista de páginas es suficiente, pero tiene que representar la jerarquía de las páginas correctamente.

2019-12-12 11:48 UTC, ainara-web commented
Ya está

2019-12-12 12:22 UTC, mberasategi commented
@ainara-web , qué es exactamente lo que "ya está"? No veo ningún cambio en este apartado desde hace 14 días.

2019-12-12 15:18 UTC, mirenbz approved these changes

2019-12-12 15:19 UTC, merged